# Generated by Django 3.0.7 on 2026-01-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_auto_20260106_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='assignment_out_of',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='exam_out_of',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
