# Generated by Django 3.0.7 on 2026-01-09 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_add_out_of_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='last_viewed_attendance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='last_viewed_results',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
