# Generated by Django 3.0.7 on 2026-01-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_auto_20260109_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentfeedback',
            name='parent_reply',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='parentfeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
