# Generated by Django 3.0.7 on 2026-01-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_auto_20260109_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentfeedback',
            name='parent_reply',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='parentfeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
