# Generated by Django 3.0.7 on 2026-03-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0014_auto_20260110_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
