# Generated by Django 3.0.7 on 2026-03-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0015_auto_20260316_1204'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancereport',
            unique_together={('student_id', 'attendance_id')},
        ),
    ]
