# Generated by Django 3.0.7 on 2026-03-16 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0016_auto_20260316_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackstudent',
            name='subject_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.Subjects'),
        ),
    ]
