# Generated by Django 3.0.7 on 2026-03-16 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0017_feedbackstudent_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackstudent',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.Staffs'),
        ),
    ]
